### .gitignore에 추가되어 git에 업로드 되지 않습니다.
### 설정 정보는 /yml/global/application-global.yml에 올려주세요.
server:
  port: 8080

spring:
  config:
    import:
      - classpath:yml/db/application-dev.yml
      - classpath:yml/db/application-local.yml
      - classpath:yml/logging/application-basic.yml
      - classpath:yml/logging/application-detailed.yml
      - classpath:yml/logging/application-persist.yml
      - classpath:yml/logging/application-custom.yml
      - classpath:yml/global/application-global.yml
  profiles:
    include: global
    group:
      default: local, custom
      develop: dev, detailed

    active: develop
