###   개인 설정이니 git에 올리지 않도록 주의해주세요 ###
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:

    hibernate:
      ddl-auto: create