spring:
  config:
    activate:
      on-profile: global
oauth:
  kakao:
    client_id: ENC(iZffJNpezuQV9MJk3R4qyU7J6nxzeZW5BPC+CYbcWEo0pqKNiG6U1HaDlBEpy2MP)
    redirect_uri: https://stamp.swygbro.com/oauth/redirected/kakao
    client_secret: ENC(8YcTJN1pWPlQAtyBYQgiAC6c/Fw4LM9oKvUVlJDeZkddcFSY6nosQuRtQbbwMlw2)
    scope: profile_nickname, profile_image, account_email


jwt:
  secret_key: ENC(2ls8XqBzzqe94En9LWK5UwWu7+n5urRLmHUi1acEI4Djgt/JtaDA3ccdZKKyst0ycCDaydJympIcdxMoAivinVQOCVgJbBdp7zTFFU0hkYc=)