###   개인 설정이니 git에 올리지 않도록 주의해주세요 ###
spring:
  config:
    activate:
      on-profile: custom
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true